name: Continuous Integration

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches: 
    - main
    - release/*
    
jobs:
  frontend:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    
    - name: Build environment
      run: docker-compose up -d --build
    
#     - name: Run environment
#       run: docker-compose up

    - name: Test
      run: yarn test --watchAll=false
